cat > docs/03-specifications/api-spec/patient-api.yaml << 'EOF'
openapi: 3.0.0
info:le: Patient API
  title: Patient API
paths:ients:
  /patients:
    get:mmary: Get patients
      summary: Get patients
      responses:
        '200':ription: Patient list
          description: Patient list
